[package]
name = "tokio-ping"
version = "0.1.1-alpha"
license = "MIT/Apache-2.0"
authors = ["Fedor Gogolev <knsd@knsd.net>"]
documentation = "https://docs.rs/tokio-ping"
repository = "https://github.com/knsd/tokio-ping"
description = "Asynchronous ICMP pinging library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
error-chain = "0.11"
futures = "0.1"
libc = "0.2"
mio = "0.6"
rand = "0.4"
socket2 = "0.3"
time = "0.1"
tokio-core = "0.1"
